### ISSUE TITLE
Provide a sample for doing login with identity and cookies in a SPA using antiforgery tokens

### ISSUE THREAD

**Issue by javiercn** [aspnet/samples#2]
We have a concrete sample of this. We just need to do some clean-up on it.

**Comment by nixa333** [comment]
I there any progress with this?

**Comment by javiercn** [comment]
We will be releasing it sometime before our 2.1 release.

**Comment by iamwyza** [comment]
Do you know roughly when this will be available?

**Comment by muratg** [comment]
@mkArtakMSFT @javiercn will this be done before 2.1.0 RTM?  Should we keep this in the milestone, or move out?

**Comment by mkArtakMSFT** [comment]
@javiercn, where are you with this issue? Did it happen?

**Comment by javiercn** [comment]
@mkArtakMSFT Nope. It got obsoleted by our 2.2 plans. This is not a recommended approach.

**Comment by iamwyza** [comment]
@javiercn - can you point to the documentation for what we should be expecting in 2.2 for this?

**Comment by javiercn** [comment]
@iamwyza The recommendation is to use tokens for authentication instead of cookies. We are including an oAuth2.0/Open ID Connect server for APIs

**Comment by niklasholm** [comment]
Well this was tremendously not useful. Any chance we can see the non-cleaned up sample @javiercn? Replacing simple cookies with OpenID Connect seems like an enormous hassle.
