### ISSUE TITLE
How to deploy Flight Finder-demo?

### ISSUE THREAD

**Issue by Axel-Joester** [aspnet/samples#47]
The blazor Flight Finder demo is a solution with three projects, FlightFinder.Server, FlightFinder.Client and FlightFinder.Shared. In visual studio 2019 I can run it without problems. However, when I deploy it to an IIS, it deploys without error, but when called stays in the "Loading..." screen forever.

I can't figure out, how to deploy this correctly. Should I just deploy the server-project? Seems not to work. Should I deploy both projects, client and server, to separate paths? Then where do I inform the client about the server location?

Please include deployment instructions.

**Comment by Axel-Joester** [comment]
I should add: deployment to the root of an dedicated site works. I just can't figure out, how to to deploy to Sub-Url of an existing site

**Comment by oatsoda** [comment]
On my travels through the documentation it talks about sub-apps in IIS:

https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.0&tabs=visual-studio#app-base-path

>In many hosting scenarios, the relative URL path to the app is the root of the app. In these cases, the app's relative URL base path is a forward slash (<base href="/" />), which is the default configuration for a Blazor app. In other hosting scenarios, such as GitHub Pages and IIS sub-apps, the app base path must be set to the server's relative URL path of the app.

Not sure if that helps?

**Comment by Axel-Joester** [comment]
Yes, that does help, thanks! 
I managed to get it to deploy now.
